name: Node 12 Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  node-12:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Node 12 Alpine
      uses: docker/build-push-action@v2
      with:
        context: ./node/12/alpine
        file: ./node/12/alpine/Dockerfile
        pull: true
        push: true
        tags: |
          full360/node:12-alpine
